Hw03 mongodb
dffleh/nodejs-rest-api pull request #2
Opened 2023-02-07 20:07 UTC by dffleh

2023-02-07 20:52 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-02-07 20:52 UTC, KhYulian commented on app.js
> +// const MongoClient = require("mongodb").MongoClient;
можете видалити. ми використовуємо mongoose

2023-02-07 20:52 UTC, KhYulian commented on routes/api/schema.js
винесіть цей файл у  /utils/validation/validationSchemas

2023-02-07 20:52 UTC, KhYulian commented on server.js
> +main();
можна використати iife

2023-02-07 20:52 UTC, KhYulian commented on routes/api/contacts.js
> +      return res.status(400).json({ message: "missing field favorite" });
створіть схему joi для оновлення поля favorite та скористайтесь

2023-02-07 22:09 UTC, dffleh commented on server.js
> +main();
не розумію як тут використати if?

2023-02-07 22:10 UTC, dffleh commented on routes/api/contacts.js
> +      return res.status(400).json({ message: "missing field favorite" });
ви напевно пропустили у мене в schema joi іде останнім 
favorite: Joi.boolean().optional().default(false),

2023-02-07 22:26 UTC, dffleh commented on app.js
> +// const MongoClient = require("mongodb").MongoClient;
Це якась перевірка через express йде обробка найголовніша це const router = express.Router();
як я можу її видалити?

2023-02-07 22:29 UTC, dffleh commented on app.js
> +// const MongoClient = require("mongodb").MongoClient;
Зрозумів)) ви за це 
// const MongoClient = require("mongodb").MongoClient;

2023-02-08 10:50 UTC, KhYulian commented on server.js
> +main();
IIFE - immediately invoked function expression

2023-02-08 10:51 UTC, KhYulian commented on routes/api/contacts.js
> +      return res.status(400).json({ message: "missing field favorite" });
Якщо використовуєте схему, то вам не потрібна ця перевірка

2023-02-08 13:23 UTC, dffleh commented on server.js
> +main();
done

2023-02-08 14:17 UTC, dffleh commented on app.js
> +// const MongoClient = require("mongodb").MongoClient;
done

2023-02-08 14:17 UTC, dffleh commented on routes/api/schema.js
done

2023-02-08 14:17 UTC, dffleh commented on routes/api/contacts.js
> +      return res.status(400).json({ message: "missing field favorite" });
done

2023-02-08 15:19 UTC, KhYulian approved these changes
Чудова робота!

2023-02-08 15:19 UTC, merged